apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-finder-webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-finder-webapp
  template:
    metadata:
      labels:
        app: car-finder-webapp
    spec:
      containers:
        - name: car-finder-webapp
          image: car-finder-webapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: car-finder-webapp-balancer
spec:
  selector:
    app: car-finder-webapp
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
